### ISSUE TITLE
Increasing upload limit

### ISSUE THREAD

**Issue by aminvakil** [aminvakil/uploader-telegram-bot#1]
Due to telegram policies you cannot send a file larger than 50MB with sendDocument() method.

I don't know how can I increase file size.

Any idea?

**Comment by anzilr** [comment]
use Telethon

**Comment by aminvakil** [comment]
I couldn't find a way to upload files via bots from telethon from these links:
https://telethon.readthedocs.io/
https://github.com/LonamiWebs/Telethon

Although I've found this repo which uses telethon for uploading but via a user.
https://github.com/Nekmo/telegram-upload

**Comment by anzilr** [comment]
I made an UserBot using this repo https://github.com/SpEcHiDe/UniBorg
Now, I'm using my own bot to download and upload files to telegram. Can you contribute to it?

**Comment by anzilr** [comment]
@aminvakil What about pyrogram? I know a bot that uses pyrogram library to upload, download, convert, and to generate public download link of a telegram file.

**Comment by aminvakil** [comment]
All your repositories are for telegram and unfortunately I couldn't find the one you want to upload files with it, can you send me the link and how can I help you?

**Comment by anzilr** [comment]
> All your repositories are for telegram and unfortunately I couldn't find the one you want to upload files with it, can you send me the link and how can I help you?

I'm personally using a modified clone of this  repo 👉🏻 https://github.com/SpEcHiDe/AnyDLBot . It's using pyrogram as it's base.

**Comment by aminvakil** [comment]
Unfortunately I don't know python and I can't contribute to your repo, but I will try to fork and use it for myself. Thanks.

**Comment by aminvakil** [comment]
There is nothing that could be done about this, feel free to create a PR if you have ideas, or check this link to see if telegram has increased their limit.
https://core.telegram.org/bots/api#senddocument
Closing this issue for now.
